CREATE TABLE `newschema`.`users` (
  `UserID` INT NOT NULL,
  `RezeptID` VARCHAR(255) NULL,
  `Kcal` VARCHAR(255) NULL,
  `Eiweis` VARCHAR(255) NULL,
  `Kohlenhydrate` VARCHAR(255) NULL,
  `Fett` VARCHAR(255) NULL,
  `Calcium` VARCHAR(255) NULL,
  `Kalium` VARCHAR(255) NULL,
  `Eisen` VARCHAR(255) NULL,
  `Zink` VARCHAR(255) NULL,
  `Magnesium` VARCHAR(255) NULL,
  `Ballaststoffe` VARCHAR(255) NULL,
  `Linolsaeure` VARCHAR(255) NULL,
  `Linolensaeure` VARCHAR(255) NULL,
  `Iodid` VARCHAR(255) NULL,
  `VitaminA` VARCHAR(255) NULL,
  `VitaminC` VARCHAR(255) NULL,
  `VitaminE` VARCHAR(255) NULL,
  `VitaminB1` VARCHAR(255) NULL,
  `VitaminB2` VARCHAR(255) NULL,
  `VitaminB6` VARCHAR(255) NULL,
  `VitaminB12` VARCHAR(255) NULL,
  `Date` DATETIME NULL);
